version: '3'

services:
  erlang:
    image: erlang:22.3
    volumes:
      - ../:/emqx_auth_pgsql
    networks:
      - app_net
    depends_on:
      - pgsql_server
    tty: true

  pgsql_server:
    build:
        context: ./pgsql
        args:
            POSTGRES_USER: postgres
            BUILD_FROM: postgres:${PGSQL_TAG}
    image: emqx_pgsql:${PGSQL_TAG}
    restart: always
    hostname: pgsql_server
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
       - "5432:5432"
    command:
       - -c
       - ssl=on
       - -c
       - ssl_cert_file=/var/lib/postgresql/server.crt
       - -c
       - ssl_key_file=/var/lib/postgresql/server.key
       - -c
       - ssl_ca_file=/var/lib/postgresql/root.crt
       - -c
       - hba_file=/var/lib/postgresql/pg_hba.conf

    networks:
      app_net:
        ipv4_address: 192.168.1.10
        ipv6_address: 2001:3200:3200::20

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
        - subnet: 2001:3200:3200::/64
    enable_ipv6: true
    driver_opts:
      com.docker.network.enable_ipv6: "true"
